# NixOS module for railscale - self-hosted Tailscale control server
#
# config options under services.railscale.settings are generated by nixcfg
# from schema.json. this module defines nix-only options and the
# systemd/firewall/user config section
#
# usage: import ./module.nix { inherit nixcfgLib schema; }
{ nixcfgLib, schema }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.railscale;
  dataDir = "/var/lib/railscale";
  runDir = "/run/railscale";

  policyJsonFile =
    if cfg.policy != null then pkgs.writeText "policy.json" (builtins.toJSON cfg.policy) else null;

  resolvedPolicyFile = if policyJsonFile != null then policyJsonFile else cfg.policyFile;

  # parse port from "host:port" string
  parsePort =
    addr: fallback:
    let
      parts = lib.splitString ":" addr;
    in
    if builtins.length parts >= 2 then lib.toIntBase10 (lib.last parts) else fallback;
in
{
  imports = [
    (nixcfgLib.mkModule {
      inherit schema;
      naming = "snake_case";
      settingsAttr = "settings";
    })
  ];

  # nix-only options (settings.* comes from nixcfg via the import above)
  options.services.railscale = {
    package = lib.mkPackageOption pkgs "railscale" { };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to open firewall ports for the embedded DERP relay and STUN server.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "railscale";
      description = "User account under which railscale runs.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "railscale";
      description = "Group under which railscale runs.";
    };

    policyFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Path to grants-based policy file (JSON format).";
    };

    policy = lib.mkOption {
      type = lib.types.nullOr (lib.types.attrsOf lib.types.anything);
      default = null;
      description = "Declarative grants-based policy as a Nix attribute set.";
    };

    adminSocket = {
      path = lib.mkOption {
        type = lib.types.path;
        default = "${runDir}/admin.sock";
        description = "Path to the admin gRPC Unix socket.";
      };

      group = lib.mkOption {
        type = lib.types.str;
        default = cfg.group;
        defaultText = lib.literalExpression "config.services.railscale.group";
        description = "Group that can access the admin socket.";
      };
    };

    configFile = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      default = nixcfgLib.mkConfigFile {
        inherit pkgs schema;
        settings = cfg.settings;
      };
      defaultText = lib.literalExpression "generated toml config from settings";
      description = "Path to the generated config file in the nix store.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !(cfg.policy != null && cfg.policyFile != null);
        message = "services.railscale.policy and services.railscale.policyFile are mutually exclusive";
      }
    ];

    users.groups.${cfg.group} = lib.mkIf (cfg.group == "railscale") { };

    users.users.${cfg.user} = lib.mkIf (cfg.user == "railscale") {
      description = "Railscale service user";
      home = dataDir;
      group = cfg.group;
      isSystemUser = true;
    };

    systemd.services.railscale = {
      description = "Railscale - Self-hosted Tailscale control server";
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      restartTriggers = [ cfg.configFile ];
      reloadTriggers = lib.optional (policyJsonFile != null) policyJsonFile;

      script = ''
        exec ${lib.getExe cfg.package} serve \
          --config ${cfg.configFile} \
          --admin-socket ${cfg.adminSocket.path} \
          ${lib.optionalString (resolvedPolicyFile != null) "--policy-file ${resolvedPolicyFile}"}
      '';

      serviceConfig = {
        User = cfg.user;
        Group = cfg.group;
        Restart = "always";
        RestartSec = "5s";
        Type = "simple";
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        StateDirectory = "railscale";
        StateDirectoryMode = "0750";
        RuntimeDirectory = "railscale";
        RuntimeDirectoryMode = "0750";
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        PrivateMounts = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectKernelLogs = true;
        ProtectControlGroups = true;
        ProtectHostname = true;
        ProtectClock = true;
        ProtectProc = "invisible";
        ProcSubset = "pid";
        RestrictNamespaces = true;
        RestrictSUIDSGID = true;
        RemoveIPC = true;
        UMask = "0077";
        NoNewPrivileges = true;
        LockPersonality = true;
        RestrictRealtime = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [
          "@system-service"
          "~@privileged"
          "@chown"
        ];
        RestrictAddressFamilies = "AF_INET AF_INET6 AF_UNIX";
        CapabilityBoundingSet = [ "CAP_CHOWN" ];
        AmbientCapabilities = [ "CAP_CHOWN" ];
      };
    };

    environment.systemPackages = [ cfg.package ];
    environment.variables.RAILSCALE_ADMIN_SOCKET = cfg.adminSocket.path;

    networking.firewall = lib.mkIf (cfg.openFirewall && cfg.settings.derp.embedded_derp.enabled) {
      allowedTCPPorts = [ (parsePort cfg.settings.derp.embedded_derp.listen_addr 3340) ];
      allowedUDPPorts = lib.optional (cfg.settings.derp.embedded_derp.stun_listen_addr != null) (
        parsePort cfg.settings.derp.embedded_derp.stun_listen_addr 3478
      );
    };
  };

  meta.maintainers = [ ];
}
